project:
  type: website
  output-dir: docs

website:
  title: "Tree-Based Methods for Statistical Learning"
  navbar:
    left:
      - icon: github
        menu:
          - text: "Source code"
            href: "https://github.com/bgreenwell/treebook"
            icon: "git"
          - text: "Report issues/errata"
            href: "https://github.com/bgreenwell/treebook/issues"
            icon: "bug"
    right:
      - href: index.qmd
        text: Home
      - text: "How to order"
        href: howtoorder.qmd  
      - text: R scripts
        href: rscripts.qmd
      - text: "Data sets"
        href: datasets.qmd 
      - text: "Errata"
        href: errata.qmd 
      - text: "Supplementary"
        href: supplementary.qmd
      # - text: "Blog"
      #   href: blog.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

